name: job-artifact
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller sha256.py -F

      - name: Upload EXE File
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows
          path: dist/sha256.exe

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller sha256.py -F

      - name: Upload Executable File
        uses: actions/upload-artifact@v4
        with:
          name: sha256-linux
          path: dist/sha256

  build-on-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller sha256.py -F

      - name: Upload Executable File
        uses: actions/upload-artifact@v4
        with:
          name: sha256-mac
          path: dist/sha256

  test-build-windows:
    runs-on: windows-latest
    needs: build-on-windows
    steps:
      - name: Download Executable File
        uses: actions/download-artifact@v4
        with:
          name: sha256-windows

      - name: Test Executable File
        run: |
          ls
          .\sha256.exe .\sha256.exe

  test-build-linux:
    runs-on: ubuntu-latest
    needs: build-on-linux
    steps:
      - name: Download Executable File
        uses: actions/download-artifact@v4
        with:
          name: sha256-linux

      - name: Test Executable File
        run: |
          ls
          chmod +x sha256
          ./sha256 sha256

  test-build-mac:
    runs-on: macos-latest
    needs: build-on-mac
    steps:
      - name: Download Executable File
        uses: actions/download-artifact@v4
        with:
          name: sha256-mac

      - name: Test Executable File
        run: |
          ls
          chmod +x sha256
          ./sha256 sha256
