name: pytest
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller .\sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows-exe
          path: dist/sha256.exe
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-linux
          path: dist/sha256
jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-mac
          path: dist/sha256

