name: pytest
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  pysha256:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: package sha256
        run: |
          pyinstaller.exe .\sha256.py -F
          cd .\dist\
      - name: run sha256
        run: .\sha256.exe .\sha256.exe
