name: pytest
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  pysha256:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller .\sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows-exe
          path: dist/sha256.exe
